### ISSUE TITLE
NameError: global name 'FileNotFoundError' is not defined

### ISSUE THREAD

**Issue by ochawkeye** [Euphe/dungeon_bot#1]
I didn't make it very far out of the blocks.

```
    P:\Projects\Home Computer\dungeon_bot>python run.py
    Traceback (most recent call last):
      File "run.py", line 3, in <module>
        from dungeon_bot.dungeon_bot import DungeonBot
      File "P:\Projects\Home     Computer\dungeon_bot\dungeon_bot\dungeon_bot.py    ", line 4, in <module>
    from .bot_events import *
      File "P:\Projects\Home Computer\dungeon_bot\dungeon_bot\bot_events.py", line 23, in <module>
        persistence_controller = PersistenceController.get_instance()
      File "P:\Projects\Home Computer\dungeon_bot\dungeon_bot\persistence.py", line 58, in get_instance
        PersistenceController.instance = PersistenceController()
      File "P:\Projects\Home Computer\dungeon_bot\dungeon_bot\persistence.py", line 11, in __init__
        self.players = self.load_players()
      File "P:\Projects\Home Computer\dungeon_bot\dungeon_bot\persistence.py", line 50, in load_players
        except FileNotFoundError:
    NameError: global name 'FileNotFoundError' is not defined
```

**Comment by Euphe** [comment]
Caused by using python 2 instead of python 3.
